config/routes.rb
Rails.application.routes.draw do

	require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
  mount Ckeditor::Engine => '/ckeditor'
  
	devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)
	resources :slides
	resources :discounts
	post '/discounts/:id/like', to: 'discounts#like', as: :discount_like

	post '/pages/save_location', to: 'pages#save_location'
	post '/pages/update_location', to: 'pages#update_location', as: :update_location
	get '/favorite-discounts', to: 'users#favorite_discounts', as: :favorite_discounts
	get '/redeem', to: 'users#redeem', as: :redeem_deals
	get '/my-purchase', to: 'users#my_purchase', as: :my_purchase
	get '/my-sales', to: 'users#my_sales', as: :my_sales
	post '/mark_deal_redeem/:item_id', to: 'users#mark_deal_redeem', as: :mark_deal_redeem
	post '/users/send_deal_as_gift/:item_id', to: 'users#send_deal_as_gift', as: :send_deal_as_gift
	get '/users/accept-deal-gift', to: 'users#accept_deal_gift', as: :accept_deal_gift

	resources :affiliates, only: []
	get '/affiliations', to: 'affiliates#index', as: :affiliations
	match 'affiliates/create_business', to: 'affiliates#create_business', as: :create_business, via: [:get, :post]
	match 'affiliates/update_business/:slug', to: 'affiliates#update_business', as: :update_business, via: [:get, :put]
	match 'affiliates/create_discount', to: 'affiliates#create_discount', as: :create_discount, via: [:get, :post]
	match 'affiliates/update_discount/:slug', to: 'affiliates#update_discount', as: :update_discount, via: [:get, :put]
	post '/pages/load_states', to: 'pages#load_states', as: :load_states
	get '/payout/request', to: 'pages#request_payout', as: :request_payout
	post 'payout/submit_request', to: 'pages#submit_payout_request', as: :submit_payout_request
	

	root 'pages#index'
	get '/search', to: 'pages#search', as: :search
	post '/subscribe', to: 'pages#subscribe', as: :subscribe

	devise_for :users,
	controllers: {registrations: :registrations, omniauth_callbacks: :omniauth_callbacks, sessions: :sessions}

	as :user do
		get "/login", to: 'sessions#new'
		post "/login", to: 'sessions#create'
		get '/join', to: 'registrations#new'
		post '/join', to: 'registrations#create'
		delete '/logout', to: 'sessions#destroy'
		get '/forgot_password', to: 'devise/passwords#new'
		post '/forgot_password', to: 'devise/passwords#create'
		get '/account', to: 'registrations#edit'
		put '/account', to: 'registrations#update'
		get '/profile', to: 'users#profile'
		get '/:type/:slug', to: 'pages#show_account', as: :show_account
		post 'update_profile', to: 'users#update_profile'
		get '/merchant_account', to: 'users#merchant_account', as: :merchant_account
	end
  get '/stripe_connect', to: 'users#stripe_connect', as: :stripe_connect
  get '/stripe_connect_callback', to: 'users#stripe_connect_callback', as: :stripe_connect_callback
  
  resources :carts, only: []
	get '/cart', to: 'carts#index', as: :carts
	post '/add_to_cart', to: 'carts#add_to_cart', as: :add_to_cart
	delete '/remove_from_cart', to: 'carts#remove_from_cart', as: :remove_from_cart
	post '/checkout', to: "carts#checkout", as: :checkout
	post '/carts/purchase', to: "carts#purchase", as: :purchase
	get '/purchase/invoice/:purchase_number', to: "carts#invoice", as: :invoice

	get '/deals', to: 'pages#discounts'
	get '/businesses', to: 'pages#businesses'
	get '/organizations', to: 'pages#organizations'
	get '/products', to: 'pages#products'

	get '/about', to: 'pages#about'
	get '/contact', to: 'pages#contact'
	get '/terms', to: 'pages#terms'
	get '/privacy', to: 'pages#privacy'
	get '/faq', to: 'pages#faq'
	get '/learn', to: 'pages#learn'
	get '/charity', to: 'pages#charity'
	get '/autism', to: 'pages#autism'
	get '/for-business', to: 'pages#for_business'
	get '/welcome-back', to: 'pages#welcome_back'

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: [:stripe_request_callback, :accept_deal_gift]

  ###########
  ## Filters
  ###########
  ############
  ## Requires
  ############
  #############
  ## Constants
  #############
  ##################
  ## Public Actions
  ##################

  
  ##update profile for Business / Organization / Agency
    def profile
    return redirect_to root_path if current_user.customer?
    @profile = current_user.profile.present? ? current_user.profile : Profile.new
    @account_type = current_user.user_type.titleize
    if @profile.try(:country).present?
      country = Country.where(name: @profile.country).first
      @states = country.states.select(:name).order(:name).pluck(:name) if country.present?
    end
    ## add breadcrumbs code
    add_breadcrumb "Home", :root_path, data: { turbolinks: false }
    add_breadcrumb "Profile" ##without link
	end

  def update_profile
    @profile = current_user.profile.present? ? current_user.profile : Profile.new
    @profile.attributes = profile_params
    @profile.user_id = current_user.id
    @profile.profile_type = current_user.user_type
    if @profile.save
      redirect_to show_account_path(@profile.profile_type, @profile.slug)
    else
      if @profile.try(:country).present?
         country = Country.where(name: @profile.country).first
         @states = country.states.select(:name).order(:name).pluck(:name) if country.present?
    end
      render action: :profile
    end
  end
  
  ##get all discount liked by any user
  def favorite_discounts
    ## add breadcrumbs code
    add_breadcrumb "Home", :root_path, data: { turbolinks: false }
    add_breadcrumb "My Favorites" ##without link
    @discounts = Discount.includes(:likes).where(active: true).paginate(page: params[:page], per_page: DEFAULT_LIMIT).where(id: current_user.likes.collect(&:discount_id))
  end

  ##get all deals purchased by any user
  def redeem
    ## add breadcrumbs code
    add_breadcrumb "Home", :root_path, data: { turbolinks: false }
    add_breadcrumb "Redeem Deals" ##without link
    render "users/customer/redeem"
    @deals = @discounts ##deal type discounts purchased by current user
  end
  
  ##merchant account
  def merchant_account
    if !current_user.business? || current_user.profile.blank? 
     return redirect_to profile_path, alert: "You must have a business profile to enable merchant account abilities."
    end
    @merchant_accounts = current_user.merchant_accounts
  end
  
  ##handle stripe connect request initiate
  def stripe_connect
    if Rails.env.development? || Rails.env.staging?
      callback_url = stripe_connect_callback_url
    else
      callback_url = "https://www.marketpad.com/stripe_connect_callback"
    end
    url = "https://connect.stripe.com/oauth/authorize?"
    query = {
      response_type: "code",
      scope: "read_write",
      stripe_landing: "register",
      client_id: ENV['STRIPE_CONNECT_CLIENT_ID'],
      redirect_uri: callback_url,
      state: current_user.id
    }.to_query
    Rails.logger.info query
    redirect_to url + query
  end

  ##handle stripe connect callback
  def stripe_connect_callback
    ##check if params state(current user id) present
    begin
      code = params[:code]
      state = params[:state]
      if params[:state].present?

        if params["error"]
          flash[:alert] = params["error_description"]
          return redirect_to merchant_account_url
        end
      
        resp = HTTParty.post("https://connect.stripe.com/oauth/token",{
          headers: {"Authorization" => "Bearer #{ENV['STRIPE_SECRET_KEY']}"},
          body: {code: code, grant_type: "authorization_code"}
        })

        if resp["error"]
          flash[:alert] = resp["error_description"]
          return redirect_to merchant_account_url
        end


        user = User.where(id: params[:state]).first
        profile = user.profile
        if profile.present?

          parsed_response = resp.parsed_response
          livemode = parsed_response['livemode'] ##live or test
          merchant_account = profile.merchant_accounts.where(livemode: livemode).first
          merchant_account =  MerchantAccount.new if merchant_account.blank?
          
          attributes = parsed_response.merge!(user_id: state, profile_id: profile.id, account_type: 'Stripe', active: true)
          merchant_account.attributes = attributes
          if merchant_account.save
            redirect_to merchant_account_url, notice: "Your stripe account has been successfully linked or updated with MarketPad."
          else
            redirect_to merchant_account_url, alert: "There is any problem while saving your stripe account details. Please try again."
          end

        end
      end
    rescue Exception => e
      Rails.logger.error "Exception Occurs:: #{e.message}"
      Airbrake.notify(e) if Rails.env.staging? || Rails.env.production?
    end
  end
  
  ##show all purchases of customer
  def my_purchase
    ## add breadcrumbs code
    add_breadcrumb "Home", :root_path, data: { turbolinks: false }
    add_breadcrumb "My Purchase" ##without link
    @items = CartItem.includes(:discount, :business, :cart).joins(:cart, :discount).where("discounts.discount_type =? AND carts.user_id = ? AND carts.paid =? OR giftee_email =?", 'deal', current_user.id, true, current_user.email).paginate(page: params[:page], per_page: DEFAULT_LIMIT).order("carts.completed_at DESC")
  end
  
  ##show business sales
  def my_sales
    return redirect_to root_path unless current_user.business? && current_user.profile.business?
    ## add breadcrumbs code
    add_breadcrumb "Home", :root_path, data: { turbolinks: false }
    add_breadcrumb "My Sales" ##without link
    @items = CartItem.includes(:discount, :business, :cart, cart: :customer).joins(:cart).where("cart_items.business_id = ? AND carts.paid =?", current_user.profile.id, true).paginate(page: params[:page], per_page: DEFAULT_LIMIT).order("carts.completed_at DESC")
    render "users/business/my_sales"
  end
  
  ##mark deal as redeemed by customer or business
  def mark_deal_redeem
    item = CartItem.where(id: params[:item_id]).first
    if item.present? && !item.redeemed? && item.deal?
      item.update(redeemed: true, redeemed_by: current_user.id, redeemed_time: Time.now)
      @success = true
    else
    end
  end

  ##send deal as gift by customer to friend
  def send_deal_as_gift
    item = CartItem.where(id: params[:item_id]).first
    if item.present? && !item.redeemed? && item.deal? && !item.gift
      if item.update(gift: true, gifter_id: current_user.id, gift_time: Time.now, giftee_email: params[:giftee_email], gifter_name: current_user.full_name)
        ##send email on giftee's email address
        NotificationMailer.delay.send_deal_as_gift(params[:giftee_name], params[:giftee_email], current_user.full_name, item.sales_purchase_number)
        flash[:notice] = "Gift sent successfully!!"
        render js: "window.location = '#{my_purchase_path}'"
      else
        flash[:alert] = "There is an issue while sending gift. Please try again."
        render js: "window.location = '#{my_purchase_path}'"
      end
    else
      flash[:alert] = "Deal is already redeemed or sent as gift."
      render js: "window.location = '#{my_purchase_path}'"
    end
  end

  def accept_deal_gift
    return redirect_to root_path if params[:giftID].blank?
    
    if current_user.blank?
      session[:deal_gift_id] = params[:giftID] 
      session[:return_url] = request.url
      return redirect_to login_path
    end

    @item = CartItem.where(sales_purchase_number: params[:giftID]).first
    return redirect_to root_path, alert: "Gift does not exist or already redeemed." if @item.blank? || @item.redeemed?

    ##check if giftee email not same as current user's email
    return redirect_to root_path, alert: "Sorry!! This gift does not belongs to you." if @item.giftee_email != current_user.email


  end


  #####################
  ## Protected Methods
  #####################
  
  protected

  ###################
  ## Private Methods
  ###################

  private

    def profile_params
      params.require(:profile).permit(:name, :description, :street, :city, :state, :zipcode, :website, :fb_link,
        :twitter_link, :google_link, :image, :cover_image, :family_friendly, :phone_number, :country, :affiliate_code)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<% if object.errors.any? %>
  <p style= "width:96%;font-size:16px; color: red;">
  	The form contains <%= pluralize(object.errors.count, "error") %>.
  </p>
  </br>
  <p style= "width:96%;font-size:16px; color: red;">
    <%= formatted_error_messages(object)%>
  </p>
  </br>
<% end %>

app/views/users/_form.html.slim
= form_for(@profile, url: update_profile_path, html: {multipart: true, method: :post, id: "progress_form"}) do |f|
	= render partial: 'users/errors', locals: {object: @profile}
	.prog-form-steps
		.prog-form-step.prog-form-step-1.is-visible
			p Tell Us About Your #{@account_type}
			.field#business-name
			  = f.text_field :name, placeholder: "#{@account_type} name"
			.field#business-description
				= f.text_area :description, placeholder: "#{@account_type} Description"
			- if business?
			  p Affiliate Code
			- if business?
				.field#business-description
				  = f.text_field :affiliate_code, placeholder: "Affiliate Code", id: "profile_aff_code"
			p Is Your #{@account_type} Family Friendly?
			.field.styled-radio#business-family
				= f.check_box :family_friendly, id: 'styled-radio', class: 'left'
				label.check-label for="styled-radio"
			.prog-form-actions
				/ .btn-secondary-ghost.prog-form-cancel BACK
				.btn.btn-primary.prog-form-next NEXT


		.prog-form-step.prog-form-step-2
			p Where is your #{@account_type} located?
			.field#business-street
				= f.text_field :street, placeholder: "#{@account_type} Address"
			.field.styled-select
			  = f.select :country, options_for_select(Country.order(:name).pluck(:name), selected: @profile.country), prompt: "> Please select a country"
			.field.styled-select
			  = render partial: "pages/states_list"
			.field#business-city
				= f.text_field :city, placeholder: "City"
						
			.field#business-zip
			  = f.text_field :zipcode, placeholder: "Zipcode"
			.prog-form-actions
				.btn-secondary-ghost.prog-form-back BACK
				.btn.btn-primary.prog-form-next NEXT


		.prog-form-step.prog-form-step-3
			p How can customers reach you?
			.field#business-phone
			  = f.text_field :phone_number, placeholder: "Phone Number"
			.field#business-website
			  = f.text_field :website, placeholder: "http://www.YourWebsite.com"
			p Are you on social media?
			.field#business-facebook
			  = f.text_field :fb_link, placeholder: "http://www.facebook.com/your-profile"
			.field#business-twitter
			  = f.text_field :twitter_link, placeholder: "http://www.twitter.com/your-profile"
			.field#business-google
			  = f.text_field :google_link, placeholder: "http://plus.google.com/your-profile"
			.prog-form-actions
				.btn-secondary-ghost.prog-form-back BACK
				.btn.btn-primary.prog-form-next NEXT


		.prog-form-step.prog-form-step-4
			p Make sure your profile looks great!
			.field#business-profile-image
				label Profile Image
				- if @profile.image?
					.form-image
						= image_tag(@profile.image.url(:medium))
				= f.file_field :image, placeholder: "Upload Profile Image", class: 'file-field'
			.field#business-cover-image
				label Cover Image
				- if @profile.cover_image?
					.form-image
						= image_tag(@profile.cover_image.url(:medium))
				= f.file_field :cover_image, placeholder: "Upload Cover Image", class: 'file-field'
			.prog-form-actions
				.btn-secondary-ghost.prog-form-back BACK
				= link_to "SAVE", "javascript:", class: "btn btn-primary prog-form-next", id: "progress_submit_btn"

javascript:
  $(function(){

    $('#profile_country').change(function(){

        country_name = $(this).val();
        profile_id = '#{@profile.try(:id)}'
	    $.ajax({
	      type: 'POST',
	      url: "/pages/load_states",
	      data: {country_name: country_name, profile_id: profile_id}
	    })
	});

  });

app/views/users/accept_deal_gift.html.slim
#redeem-index
	section.redeem-info
		.container-narrow
			h3.center My Gift
	section.container
			table.deal-redeem-table
				thead
					tr
						th Image
						th Name
						th Gifter Name
						th Merchant
						th Gift Date
						th Sales Purchase No.
						th 
				tbody.deal-redeem-list
					tr.deal-redeem-item
						td =image_tag @item.discount.image_url(:medium), class: "cart-discount-image"
						td=@item.discount.name
						td=@item.gifter_name
						td=@item.business.name
						td=@item.gift_time.strftime("%b, %d %Y")
						td=@item.sales_purchase_number
						td.redeem-btn id="redeem_item_#{@item.id}"
							- if @item.redeemed?
								=link_to "Redeemed", "javascript:", style: "color:red;"
							- else
								=link_to "Redeem", mark_deal_redeem_path(@item), remote: true, method: :post, data: {confirm: "Are you sure you want to redeem this deal now? This can only be done once!"}, class: 'btn btn-primary'

app/views/users/favorite_discounts.html.slim
section.discounts-gallery
  .discount-category-block
    - @discounts.each do |discount|
      .discount-card.bx-shadow-2
        = link_to discount_path(discount.slug)
          .discount-card-image style="background-image:url(#{discount.image});"
        = link_to discount_path(discount.slug)
          .discount-card-info.dark
            - if discount.family_friendly?             
              i.ion-ios-people
              i.ion-checkmark-circled
            h2 = discount.name
            p = truncate(discount.description.html_safe, :length => 45)
            
        .discount-card-buy
          p.small 
            | was 
            span 
              | $
              = discount.price
          .discount-card-buy-button.btn-primary 
            | $
            = discount.discounted_price
        .discount-card-love
          = link_to discount_like_path(discount.slug), method: :post, remote: true, id: "discount_like_#{discount.id}"
            - if current_user && discount.liked?(current_user.id)
              i.ion-ios-heart
            - else
              i.ion-ios-heart-outline
              
  = will_paginate @discounts

app/views/users/mark_deal_redeem.js.erb
<% if @success %>
  $('#redeem_item_'+'<%= params[:item_id] %>').html("<a href=javascript: style=color:red;>Redeemed</a>");
<% else %>
<% end %>

app/views/users/merchant_account.html.slim
section
	.container-narrow
		.stripe-connect-div
			h1.center Connect to Stripe 
			p.center Link Your Stripe Merchant Account with MarketPad to recieve payments instantly whenever you sell a Deal or Product!
			.stripe-connect-btn
				=link_to image_tag('stripe_connect'), stripe_connect_path

section
	.container-narrow
		table#cart-items-list
			thead.table-head
				tr.cart-header
					th Stripe Publishable Key
					th Access Token
					th Active
					th Stripe User ID
					th Live Account
			tbody.table-body 
		    - @merchant_accounts.each do |account|
					tr.cart-item
						td= account.stripe_publishable_key[0..10]
						td= account.access_token[0..10]
						td= account.active ? "Yes" : "No"
						td= account.stripe_user_id[0..10]
						td= account.livemode ? "Yes" : "No"

app/views/users/my_purchase.html.slim
#redeem-index
	section.redeem-info
		.container-narrow
			h3.center My Deals
			p.center Below are all of the Deals you've purchased on MarketPad. To Redeem your Deals, simply open this page on your phone at the time of final transaction, and allow the business owner/asssociate to press the "Redeem" button next to the Deal you want to use.
	section.container
			table.deal-redeem-table
				thead
					tr
						th Image
						th Name
						/ th Type
						th Merchant
						th Sales Purchase No.
						th Price
						th Purchase Date / Gift Date
						th Redeemed Date
						th
						th 
				tbody.deal-redeem-list
					- @items.each do |item|
						tr.deal-redeem-item
							td =image_tag item.discount.image_url(:medium), class: "cart-discount-image"
							td=item.discount.name
							/ td=item.discount.discount_type
							td=item.business.name
							td=item.sales_purchase_number
							td=number_to_currency(item.total_price)
							td=item.cart.completed_at.strftime("%b, %d %Y")
							td=item.redeemed_time.strftime("%b, %d %Y") if item.redeemed_time.present?
							td.redeem-btn
								- if item.cart.try(:user_id) == current_user.id
									- if item.deal?
										- if item.redeemed?
										- else
										  - if item.gift
										    =link_to "Gift Sent", "javascript:", style: "color:red;"
										  - else
											  =link_to "Gift", "javascript:", class: 'btn btn-secondary gift-item', id: "gift_#{item.id}"
									.gift-modal id= "gift_modal_#{item.id}"
										i.ion-close
										=form_tag(send_deal_as_gift_path(item.id), remote: true)
											p.center Please enter the name and email of the gift recipient below.
											.field
												input type='text' placeholder="Friend's Name" required="true" name= 'giftee_name'
											.field
												input type='email' placeholder="Friend's Email" required="true" name="giftee_email"
												= button_tag "Send Gift", class: "btn btn-primary", data: {disable_with: "Sending..."}
							td.redeem-btn id="redeem_item_#{item.id}"
								- if item.deal?
									- if item.redeemed?
										=link_to "Redeemed", "javascript:", style: "color:red;"
									- else
										=link_to "Redeem", mark_deal_redeem_path(item), remote: true, method: :post, data: {confirm: "Are you sure you want to redeem this deal now? This can only be done once!"}, class: 'btn btn-primary'

				= will_paginate @items

javascript:
  $('.gift-item').click(function(){
    id = $(this).attr("id").split("_")[1];
    $('.gift-modal').hide();
    $('#gift_modal_'+id).show();
  });

  $('.ion-close').click(function(){
    $('.gift-modal').hide();
  });

app/views/users/profile.html.slim
section#new-business
	.container
		.center.user-upgrade-form
			.prog-form
				.prog-form-head
					.prog-form-title
						h1 Complete Your #{@account_type} Profile
						p Please fill all sections of this form.
					.prog-form-progress
						.prog-circle.is-active
							i.ion-ios-information-outline
						.prog-circle
							i.ion-ios-location-outline
						.prog-circle
							i.ion-ios-world-outline
						.prog-circle
							i.ion-ios-camera-outline
				.prog-form-body
					= render 'users/form'
					.center
						= link_to 'Abort!', root_path, data: { turbolinks: false }