config/routes.rb
Rails.application.routes.draw do

	require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
  mount Ckeditor::Engine => '/ckeditor'
  
	devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)
	resources :slides
	resources :discounts
	post '/discounts/:id/like', to: 'discounts#like', as: :discount_like

	post '/pages/save_location', to: 'pages#save_location'
	post '/pages/update_location', to: 'pages#update_location', as: :update_location
	get '/favorite-discounts', to: 'users#favorite_discounts', as: :favorite_discounts
	get '/redeem', to: 'users#redeem', as: :redeem_deals
	get '/my-purchase', to: 'users#my_purchase', as: :my_purchase
	get '/my-sales', to: 'users#my_sales', as: :my_sales
	post '/mark_deal_redeem/:item_id', to: 'users#mark_deal_redeem', as: :mark_deal_redeem
	post '/users/send_deal_as_gift/:item_id', to: 'users#send_deal_as_gift', as: :send_deal_as_gift
	get '/users/accept-deal-gift', to: 'users#accept_deal_gift', as: :accept_deal_gift

	resources :affiliates, only: []
	get '/affiliations', to: 'affiliates#index', as: :affiliations
	match 'affiliates/create_business', to: 'affiliates#create_business', as: :create_business, via: [:get, :post]
	match 'affiliates/update_business/:slug', to: 'affiliates#update_business', as: :update_business, via: [:get, :put]
	match 'affiliates/create_discount', to: 'affiliates#create_discount', as: :create_discount, via: [:get, :post]
	match 'affiliates/update_discount/:slug', to: 'affiliates#update_discount', as: :update_discount, via: [:get, :put]
	post '/pages/load_states', to: 'pages#load_states', as: :load_states
	get '/payout/request', to: 'pages#request_payout', as: :request_payout
	post 'payout/submit_request', to: 'pages#submit_payout_request', as: :submit_payout_request
	

	root 'pages#index'
	get '/search', to: 'pages#search', as: :search
	post '/subscribe', to: 'pages#subscribe', as: :subscribe

	devise_for :users,
	controllers: {registrations: :registrations, omniauth_callbacks: :omniauth_callbacks, sessions: :sessions}

	as :user do
		get "/login", to: 'sessions#new'
		post "/login", to: 'sessions#create'
		get '/join', to: 'registrations#new'
		post '/join', to: 'registrations#create'
		delete '/logout', to: 'sessions#destroy'
		get '/forgot_password', to: 'devise/passwords#new'
		post '/forgot_password', to: 'devise/passwords#create'
		get '/account', to: 'registrations#edit'
		put '/account', to: 'registrations#update'
		get '/profile', to: 'users#profile'
		get '/:type/:slug', to: 'pages#show_account', as: :show_account
		post 'update_profile', to: 'users#update_profile'
		get '/merchant_account', to: 'users#merchant_account', as: :merchant_account
	end
  get '/stripe_connect', to: 'users#stripe_connect', as: :stripe_connect
  get '/stripe_connect_callback', to: 'users#stripe_connect_callback', as: :stripe_connect_callback
  
  resources :carts, only: []
	get '/cart', to: 'carts#index', as: :carts
	post '/add_to_cart', to: 'carts#add_to_cart', as: :add_to_cart
	delete '/remove_from_cart', to: 'carts#remove_from_cart', as: :remove_from_cart
	post '/checkout', to: "carts#checkout", as: :checkout
	post '/carts/purchase', to: "carts#purchase", as: :purchase
	get '/purchase/invoice/:purchase_number', to: "carts#invoice", as: :invoice

	get '/deals', to: 'pages#discounts'
	get '/businesses', to: 'pages#businesses'
	get '/organizations', to: 'pages#organizations'
	get '/products', to: 'pages#products'

	get '/about', to: 'pages#about'
	get '/contact', to: 'pages#contact'
	get '/terms', to: 'pages#terms'
	get '/privacy', to: 'pages#privacy'
	get '/faq', to: 'pages#faq'
	get '/learn', to: 'pages#learn'
	get '/charity', to: 'pages#charity'
	get '/autism', to: 'pages#autism'
	get '/for-business', to: 'pages#for_business'
	get '/welcome-back', to: 'pages#welcome_back'

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	##########
  ## Filters
  ###########
  before_action :authenticate_user!, except: [:index, :add_to_cart, :remove_from_cart, :checkout]
  before_action :set_discount, :set_seller, only: [:add_to_cart]
  before_action :set_cart_item, only: [:remove_from_cart]
  before_action :set_cart, only: [:add_to_cart, :remove_from_cart]
   
  ############
  ## Requires
  ############
  #############
  ## Constants
  #############
  ##################
  ## Public Actions
  ##################
  
  ##render carts page with cart items
  def index
    if session[:user_cart].present?
      cart_ids = []
      session[:user_cart].each {|uc| cart_ids << uc.values[1]}
    end
    @carts = Cart.where(id: cart_ids).includes(:cart_items, cart_items: [:discount, :business, :seller] ).order("created_at asc")
    #@cart_items = @cart.cart_items.includes(:discount, :business, :seller).order("created_at asc") if @cart.present?
  end

  def add_to_cart
    return redirect_to discount_path(@discount), alert: "Sorry!! this discount is marked as sold out. Please add other discounts in your cart." if @discount.sold_out? 
    item = @cart.cart_items.build(discount_id: @discount.id, business_id: @discount.business.id,
      sold_by: @sold_by, seller_id: @seller_id, price: @discount.discounted_price.to_f,
      total_price: @discount.discounted_price.to_f, taxes: 0.0, shipping: 0.0, sales_purchase_number: generate_item_id)
    
    @cart.sub_total = @cart.sub_total + @discount.discounted_price
    @cart.taxes = 0.0
    @cart.shipping = 0.0
    @cart.total_price = (@cart.sub_total + @cart.taxes + @cart.shipping)
    @cart.application_fees = @cart.application_fees + calculate_application_fees(item)

    if @cart.save
      redirect_to carts_path, notice: "Item added successfully!!"
    else
      redirect_to request.referer, alert: "Item could not be added in cart. Please try again."
    end
  end

  def remove_from_cart
    item = @cart_item
  	if @cart_item && @cart_item.destroy
      @cart.application_fees = @cart.application_fees - calculate_application_fees(item)
      recalculate_cart_prices(@cart.cart_items)
  	  redirect_to carts_path, notice: "Item removed from cart successfully!!"
  	else
  		redirect_to carts_path, alert: "Item could not be removed from cart. Please try again."
  	end
  end

  def checkout
    if current_user.blank?
      session[:return_url] = request.referer
      return redirect_to login_path
    else
      @cart = Cart.where(id: params[:cartID]).first
      return redirect_to carts_path if @cart.blank?
      @cart.update_column(:user_id, current_user.id) if @cart.user_id.blank? ##update user_id
      @cart_items = @cart.cart_items.includes(:discount, :business, :seller).order("created_at asc")
      
      ##check if cart changed (any item is sold out that exist in current cart)
      cart_has_changed = cart_changed
      if cart_has_changed
        flash[:alert] = "Sorry!! some of the discount are marked as sold out and removed from your cart. Please review your cart and add more discounts."
        return redirect_to carts_path
      end

      customer_discount_purchase_limit = check_customer_discount_purchase_limit
      if customer_discount_purchase_limit
        flash[:alert] = "Sorry!! some of the discount purchase maximum limit is reached and removed from your cart. Please review your cart and add more discounts."
        return redirect_to carts_path
      end

      return redirect_to carts_path, alert: "Cart is empty. Add some deals to your cart!" if @cart_items.blank?
    end
  end

  def purchase
    @cart = Cart.where(id: params[:cartID]).first
    return redirect_to carts_path if @cart.blank?
    @cart_items = @cart.cart_items.includes(:discount, :business)
    business = @cart_items.first.business

    # ##check if cart changed (any item is sold out that exist in current cart)
    # cart_has_changed = cart_changed
    # if cart_has_changed
    #   flash[:alert] = "Sorry!! some of the discounts are marked as sold out and removed from your cart. Please review your cart and add more discounts."
    #   return redirect_to carts_path
    # end

    # customer_discount_purchase_limit = check_customer_discount_purchase_limit
    # if customer_discount_purchase_limit
    #   flash[:alert] = "Sorry!! some of the discount purchase maximum limit is reached and removed from your cart. Please review your cart and add more discounts."
    #   return redirect_to carts_path
    # end
    
    begin

      merchant_accounts = business.merchant_accounts
      if merchant_accounts.present?
        if Rails.env.development? || Rails.env.staging?
          merchant_account = merchant_accounts.where(livemode: false).first
        else
          merchant_account = merchant_accounts.where(livemode: true).first
        end
      else
        return redirect_to carts_path, alert: "Sorry!! Payment to this merchant is not alloweds. Please add discounts / products from other merchant."
      end

      # Amount in cents
      amount_in_cents = (@cart.total_price.to_f * 100).to_i
      application_fee = (@cart.application_fees.to_f * 100).to_i

      #customer = Stripe::Customer.create(description: current_user.email, email: current_user.email, source: params[:stripeToken])
      
      ##get application_fee should be 6% (seller + marketpad + pool + affiliate)
      
      charge = Stripe::Charge.create({source: params[:stripeToken], amount: amount_in_cents, 
        description: "MarketPad purchased, purchase number: #{@cart.purchase_number}", 
        currency: 'usd', application_fee: application_fee}, 
        stripe_account: merchant_account.stripe_user_id
      )
      
      Rails.logger.info "Cart Response for #{@cart.purchase_number}::  #{charge} and #{charge.status}"
      ##update cart paid as true
      if charge.status == "succeeded" || charge.status == "paid"

        @cart.update(paid: true, completed_at: Time.now)
        
        ship_addr = nil
        ship_addr = ShippingAddress.create(ship_add_params) if params[:ship_add].present?

        ##remove hash from session
        session[:user_cart].delete_if {|uc| uc["#{business.id}_business_id"] == business.id || uc["#{business.id}_cart_id"] == @cart.id }
       
        ##check and mark discount as sold out and set expiry date
        ##default expiry date Date of sold out + 10 days
        if Rails.env.production?
          @cart.delay.check_discounts_sold_out
          ##calculate sales payouts
          @cart.delay.calculate_payout
          ##send email to business of product sales
          @cart.delay.send_products_sale_to_business if @cart.product_exist_in_cart?         
          ##later we move this email to delay
          NotificationMailer.delay.customer_purchase_receipt(@cart, current_user, ship_addr)
        else
          @cart.check_discounts_sold_out
          @cart.calculate_payout
          @cart.send_products_sale_to_business if @cart.product_exist_in_cart?         
          NotificationMailer.customer_purchase_receipt(@cart, current_user, ship_addr).deliver_now
        end
      
        session[:user_cart] = nil if session[:user_cart].size == 0
    
        redirect_to invoice_path(@cart.purchase_number), notice: "Thank You for your order with Marketpad!! An order receipt has been sent on your email."

      else
        redirect_to carts_path, alert: "Error while attempting payment. Please try again later."
      end

    rescue Stripe::StripeError => e
      flash[:alert] = e.message
      redirect_to carts_path
    end

  end

  def invoice
    cart_id = params[:purchase_number].sub!(/^[0]+/,'') if params[:purchase_number].present?
    @cart = Cart.where(id: cart_id).first
    return redirect_to root_path if @cart.blank? || @cart.unpaid?
    return redirect_to root_path if @cart.customer.try(:id) != current_user.id
    @cart_items = @cart.cart_items
  end
  
  ##check if any of item(discount) sold out then remove that item from cart
  def cart_changed
    cart_has_changed = false
    @cart_items.each do |item|
      if item.discount.sold_out?
        @cart.application_fees = @cart.application_fees - calculate_application_fees(item)
        item.destroy
        recalculate_cart_prices(@cart.cart_items)
        cart_has_changed = true
      end
    end
    
   cart_has_changed
  end

  ##check if customer has reached to maximum limit for discount
  def check_customer_discount_purchase_limit
    customer_limit_reached = false
    @cart_items.each do |item|
      if item.discount.cusomter_limit_reached_for_discount?(current_user.id)
        @cart.application_fees = @cart.application_fees - calculate_application_fees(item)
        item.destroy
        recalculate_cart_prices(@cart.cart_items)
        customer_limit_reached = true
      end
    end
    
   customer_limit_reached
  end

  #####################
  ## Protected Methods
  #####################
  protected

  ###################
  ## Private Methods
  ###################
  private
    
    ##calculate application fess for each item
    def calculate_application_fees(item)
      if item.product? && item.product_extra_price_present?
        extra_price = item.discount.extra_price
        ((item.total_price * 6) / 100).to_f + extra_price
      else
        ((item.total_price * 6) / 100).to_f
      end
    end
    
    ##generate unique cart item ID
    def generate_item_id
      [SecureRandom.hex(4), @cart.purchase_number].join("-")
    end


    def ship_add_params
      params.require(:ship_add).permit(:first_name, :last_name, :street_1, :street_2, :city, :state, :zipcode, :country, :phone_number, :cart_id)
    end

    def recalculate_cart_prices(cart_items)
      @cart.sub_total = cart_items.sum(:price)
      @cart.taxes = cart_items.sum(:taxes)
      @cart.shipping = cart_items.sum(:shipping)
      @cart.total_price = cart_items.sum(:total_price)
      @cart.save
    end
  
    def set_discount

app/views/carts/_cart-items.slim
.cart-section.clearfix
	h3
		| Checkout with 
		= cart.cart_items.first.business.name

	table#cart-items-list
		thead.table-head
			tr.cart-header
				th Image
				th Name
				th.hide-tablet Merchant
				th.hide-tablet Seller
				th Price
				th
		tbody.table-body 
		- cart.cart_items.each do |item|
				tr.cart-item
					td =image_tag item.discount.image_url(:medium), class: "cart-discount-image"
					td = item.discount.name
					td.hide-tablet = item.business.name
					td.hide-tablet = item.seller_name
					td = number_to_currency(item.price)
					td = link_to content_tag('i','',class:'ion-ios-close-empty'), remove_from_cart_path(itemID: item.id), data: { confirm: "Are you sure?"}, method: :delete
		tfoot.table-foot.hide-tablet
			tr.cart-sub-total
				td.tfoot-label colspan='4' Sub Total:
				td colspan='1' =number_to_currency(cart.sub_total)
			tr.cart-shipping
				td.tfoot-label colspan='4' Shipping:
				td colspan='1' =number_to_currency(cart.shipping)
			tr.cart-tax
				td.tfoot-label colspan='4' Taxes:
				td colspan='1' =number_to_currency(cart.taxes)
			tr.cart-total
				td.tfoot-label colspan='4' &nbsp;
				td colspan='1' 
					p =number_to_currency(cart.total_price)
		tfoot.table-foot.show-tablet
			tr.cart-sub-total
				td.tfoot-label colspan='1' Sub Total:
				td colspan='1' =number_to_currency(cart.sub_total)
			tr.cart-shipping
				td.tfoot-label colspan='1' Shipping:
				td colspan='1' =number_to_currency(cart.shipping)
			tr.cart-tax
				td.tfoot-label colspan='1' Taxes:
				td colspan='1' =number_to_currency(cart.taxes)
			tr.cart-total
				td.tfoot-label colspan='1' &nbsp;
				td colspan='1' 
					p =number_to_currency(cart.total_price)

	= form_tag checkout_path, class: 'clearfix'
		= hidden_field_tag "cartID", cart.id
		= button_tag "CHECKOUT", class: 'btn btn-primary right'
	.cart-secured.right
		i.right.ion-ios-locked-outline
		h3.right Secured by Stripe

app/views/carts/_data.html.slim
- @carts.each do |cart|
	= render partial: 'carts/cart-items', locals: {cart: cart} if cart.cart_items.present?
	

app/views/carts/_shipping_info.html.erb
</br></br>
<h2>Shipping Address</h2>
</br></br>
<%= hidden_field_tag "ship_add[cart_id]", @cart.id %>
<div class="field">
  <label>First Name</label>
  <%= text_field_tag "ship_add[first_name]", nil, required: true %>
</div>

<div class="field">
  <label>Last Name</label>
  <%= text_field_tag "ship_add[last_name]", nil, required: true %>
</div>

<div class="field">
  <label>Street1</label>
  <%= text_field_tag "ship_add[street_1]", nil, required: true %>
</div>

<div class="field">
  <label>Street2</label>
  <%= text_field_tag "ship_add[street_2]", nil, required: false %>
</div>

<div class="field">
  <label>City</label>
  <%= text_field_tag "ship_add[city]", nil, required: true %>
</div>

<div class="field">
  <label>State</label>
  <%= text_field_tag "ship_add[state]", nil, required: true %>
</div>

<div class="field">
  <label>Zip Code</label>
  <%= text_field_tag "ship_add[zipcode]", nil, required: true %>
</div>

<div class="field">
  <label>Country</label>
  <%= text_field_tag "ship_add[country]", nil, required: true %>
</div>

<div class="field">
  <label>Phone Number</label>
  <%= text_field_tag "ship_add[phone_number]", nil, required: true %>
</div>

app/views/carts/checkout.html.erb
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
    // this identifies your website in the createToken call below
    Stripe.setPublishableKey("<%= ENV['STRIPE_PUBLISH_KEY'] %>");

    function stripeResponseHandler(status, response) {
        if (response.error) {
            // re-enable the submit button
            $('.submit-button').removeAttr("disabled");
            // show the errors on the form
            $(".payment-errors").html(response.error.message);
        } else {
            var form$ = $("#payment-form");
            // token contains id, last4, and card type
            var token = response['id'];
            // insert the token into the form so it gets submitted to the server
            form$.append("<input type='hidden' name='stripeToken' value='" + token + "' />");
            // and submit
            $('#payment_submit').attr("disabled", "disabled");
            form$.get(0).submit();
        }
    }

    $(document).ready(function() {
        $("#payment-form").submit(function(event) {
            // disable the submit button to prevent repeated clicks
            $('.submit-button').attr("disabled", "disabled");
            // createToken returns immediately - the supplied callback submits the form if there are no errors
            Stripe.createToken({
                number: $('.card-number').val(),
                cvc: $('.card-cvc').val(),
                exp_month: $('.card-expiry-month').val(),
                exp_year: $('.card-expiry-year').val()
            }, stripeResponseHandler);
            return false; // submit from callback
        });
    });

</script>
<section id="shopping-cart">
  <div class="container-narrow">
    <div class="cart-wrap clearfix">
      <div class="center cart-title">
        <i class="ion-android-cart"></i>
        <h2> Secure Checkout </h2>
        <p class="cart-review"> Please enter your billing information below.</p>
        <div class="payment-icons">
          <span class="payment-icon"><%= image_tag('icons/Safe.png') %></span>
          <span class="payment-icon"><%= image_tag('icons/mastercard.png') %></span>
          <span class="payment-icon"><%= image_tag('icons/VISA.png') %></span>
          <span class="payment-icon"><%= image_tag('icons/Cirrus.png') %></span>
          <span class="payment-icon"><%= image_tag('icons/American Express.png') %></span>
        </div>
      </div>
      <span class="payment-errors" style="color:red;"></span>
      <%= form_tag purchase_path, id: "payment-form" do %>
        <%= hidden_field_tag "cartID", @cart.id %>
        <div class="field">
          <label>Card Number</label>
          <input type="text" maxlength="16" autocomplete="off" class="card-number" />
        </div>
        <div class="field">
          <label>CVC</label>
          <input type="text" maxlength="3" autocomplete="off" class="card-cvc" />
        </div>
        <div class="field">
          <label>Expiration (MM/YY)</label>
          <select maxlength="2" class="card-expiry-month"/>
            <option value=''>--Select Month--</option>
            <option selected value='01'>01 - Janaury</option>
            <option value='02'>02 - February</option>
            <option value='03'>03 - March</option>
            <option value='04'>04 - April</option>
            <option value='05'>05 - May</option>
            <option value='06'>06 - June</option>
            <option value='07'>07 - July</option>
            <option value='08'>08 - August</option>
            <option value='09'>09 - September</option>
            <option value='10'>10 - October</option>
            <option value='11'>11 - November</option>
            <option value='12'>12 - December</option>
          </select>
          <select maxlength="2" class="card-expiry-year"/>            
            <option value=''>--Select Year--</option>
            <option selected value='17'>2017</option>
            <option value='18'>2018</option>
            <option value='19'>2019</option>
            <option value='20'>2020</option>
            <option value='21'>2021</option>
            <option value='22'>2022</option>
            <option value='23'>2023</option>
            <option value='24'>2024</option>
            <option value='25'>2025</option>
            <option value='26'>2026</option>
            <option value='27'>2027</option>
            <option value='28'>2028</option>
            <option value='28'>2029</option>
            <option value='28'>2030</option>
          </select>
        </div>

        <% if @cart.product_exist_in_cart? %>
         <%= render partial: "carts/shipping_info" %>        
        <% end %>

        <button type="submit" class="submit-button btn btn-primary" id= "payment_submit">Pay <%= number_to_currency(@cart.total_price) %></button>
      <% end %>
    </div>
  </div>

</section>

app/views/carts/index.slim
- if @carts.present?
	section#shopping-cart
		.container-narrow
			.cart-wrap.clearfix
				.center.cart-title
					i.ion-android-cart
					h2 Shopping Cart
					p.cart-review Please review the items in your cart before proceeding to secure checkout on the next page.
					- if @carts.count > 1
						.stripe-cart-help.center.secondary
							p.center 
								span.strong ATTN: 
								| If you have added items from multiple businesses, you must complete a checkout process from each business individually. We're very sorry for this inconvenience. This is due to the limitations of our secure payment processor and we are currently researching solutions to better serve your experience on MarketPad!

				= render 'carts/data'
			
- if @carts.blank?
	section#shopping-cart
		.container-narrow
			p.large Add some deals to your cart!

app/views/carts/invoice.html.slim
section#shopping-cart
	.container-narrow
		.cart-wrap.clearfix
			.center.cart-title
				i.ion-android-cart
				h2 My Receipt
				p.cart-review You should receive an email with your purchase information soon. If you do not see it in the next 30 minutes, be sure to check your junk/spam folder. Please take a screenshot of this page to save for your records.
			table#cart-items-list
				thead.table-head
					tr.cart-header
						th Image
						th Name
						th Type
						th Merchant
						th Seller
						th Price
				tbody.table-body 
			    - @cart_items.each do |item|
						tr.cart-item
							td =image_tag item.discount.image_url(:medium), class: "cart-discount-image"
							td= item.discount.name
							td= item.discount.discount_type
							td= item.business.name
							td= item.seller_name
							td= number_to_currency(item.total_price)
				tfoot.table-foot
					tr.cart-sub-total
						td.tfoot-label colspan='5' Sub Total:
						td colspan='1' =number_to_currency(@cart.sub_total)
					tr.cart-shipping
						td.tfoot-label colspan='5' Shipping:
						td colspan='1' =number_to_currency(@cart.shipping)
					tr.cart-tax
						td.tfoot-label colspan='5' Taxes:
						td colspan='1' =number_to_currency(@cart.taxes)
					tr.cart-total
						td.tfoot-label colspan='5' Amount Paid;
						td colspan='1' =number_to_currency(@cart.total_price)
			- if session[:user_cart].present? && session[:user_cart].size > 0
				.left
					= link_to "<< Continue Shopping", carts_path, class: 'btn-primary'
			.right
				= link_to "Redeem My Deals", my_purchase_path, class: 'btn-secondary'