config/routes.rb
Rails.application.routes.draw do

	require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
  mount Ckeditor::Engine => '/ckeditor'
  
	devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)
	resources :slides
	resources :discounts
	post '/discounts/:id/like', to: 'discounts#like', as: :discount_like

	post '/pages/save_location', to: 'pages#save_location'
	post '/pages/update_location', to: 'pages#update_location', as: :update_location
	get '/favorite-discounts', to: 'users#favorite_discounts', as: :favorite_discounts
	get '/redeem', to: 'users#redeem', as: :redeem_deals
	get '/my-purchase', to: 'users#my_purchase', as: :my_purchase
	get '/my-sales', to: 'users#my_sales', as: :my_sales
	post '/mark_deal_redeem/:item_id', to: 'users#mark_deal_redeem', as: :mark_deal_redeem
	post '/users/send_deal_as_gift/:item_id', to: 'users#send_deal_as_gift', as: :send_deal_as_gift
	get '/users/accept-deal-gift', to: 'users#accept_deal_gift', as: :accept_deal_gift

	resources :affiliates, only: []
	get '/affiliations', to: 'affiliates#index', as: :affiliations
	match 'affiliates/create_business', to: 'affiliates#create_business', as: :create_business, via: [:get, :post]
	match 'affiliates/update_business/:slug', to: 'affiliates#update_business', as: :update_business, via: [:get, :put]
	match 'affiliates/create_discount', to: 'affiliates#create_discount', as: :create_discount, via: [:get, :post]
	match 'affiliates/update_discount/:slug', to: 'affiliates#update_discount', as: :update_discount, via: [:get, :put]
	post '/pages/load_states', to: 'pages#load_states', as: :load_states
	get '/payout/request', to: 'pages#request_payout', as: :request_payout
	post 'payout/submit_request', to: 'pages#submit_payout_request', as: :submit_payout_request
	

	root 'pages#index'
	get '/search', to: 'pages#search', as: :search
	post '/subscribe', to: 'pages#subscribe', as: :subscribe

	devise_for :users,
	controllers: {registrations: :registrations, omniauth_callbacks: :omniauth_callbacks, sessions: :sessions}

	as :user do
		get "/login", to: 'sessions#new'
		post "/login", to: 'sessions#create'
		get '/join', to: 'registrations#new'
		post '/join', to: 'registrations#create'
		delete '/logout', to: 'sessions#destroy'
		get '/forgot_password', to: 'devise/passwords#new'
		post '/forgot_password', to: 'devise/passwords#create'
		get '/account', to: 'registrations#edit'
		put '/account', to: 'registrations#update'
		get '/profile', to: 'users#profile'
		get '/:type/:slug', to: 'pages#show_account', as: :show_account
		post 'update_profile', to: 'users#update_profile'
		get '/merchant_account', to: 'users#merchant_account', as: :merchant_account
	end
  get '/stripe_connect', to: 'users#stripe_connect', as: :stripe_connect
  get '/stripe_connect_callback', to: 'users#stripe_connect_callback', as: :stripe_connect_callback
  
  resources :carts, only: []
	get '/cart', to: 'carts#index', as: :carts
	post '/add_to_cart', to: 'carts#add_to_cart', as: :add_to_cart
	delete '/remove_from_cart', to: 'carts#remove_from_cart', as: :remove_from_cart
	post '/checkout', to: "carts#checkout", as: :checkout
	post '/carts/purchase', to: "carts#purchase", as: :purchase
	get '/purchase/invoice/:purchase_number', to: "carts#invoice", as: :invoice

	get '/deals', to: 'pages#discounts'
	get '/businesses', to: 'pages#businesses'
	get '/organizations', to: 'pages#organizations'
	get '/products', to: 'pages#products'

	get '/about', to: 'pages#about'
	get '/contact', to: 'pages#contact'
	get '/terms', to: 'pages#terms'
	get '/privacy', to: 'pages#privacy'
	get '/faq', to: 'pages#faq'
	get '/learn', to: 'pages#learn'
	get '/charity', to: 'pages#charity'
	get '/autism', to: 'pages#autism'
	get '/for-business', to: 'pages#for_business'
	get '/welcome-back', to: 'pages#welcome_back'

end

app/models/discount.rb
class Discount < ApplicationRecord

  include PgSearch
  multisearchable against: [:name, :description], using: { tsearch: {any_word: true, prefix: true } , trigram: {:threshold => 0.1}}, if: :active?
  #pg_search_scope :custom_search, :against => [:name, :description], if: :active?

  mount_uploader :image, DiscountImageUploader

  validates :name, :description, :image, :price, :discounted_price, :discount_type, :business_id, :limit, :limit_per_customer, presence: true

  belongs_to :business, class_name: "Profile", foreign_key: :business_id
  has_many :likes
  has_and_belongs_to_many :categories
  has_many :cart_items

  DISCOUNT_TYPES = [['Deal', 'deal'], ['Product', 'product']]
  
  after_save :create_slug, :save_pg_search_category

  scope :only_active, -> { where(discount_type: 'deal', active: true) }
  scope :only_active_products, -> { where(discount_type: 'product', active: true) }

  geocoded_by :address

  attr_accessor :default_terms_conditions

  def address
    [business.street, business.city, business.state, business.zipcode, business.country].compact.join(', ')
  end

  def to_param
    slug
  end

  def affiliated_by?(user_affiliated_code)
    affiliate_code == user_affiliated_code
  end

  def owned_by?(user)
  	business_id == user.try(:profile).try(:id)
  end

  ##check if discount is already liked by a user
  def liked?(user_id)
    likes.collect(&:user_id).include?(user_id)
  end
  
  ##method return true / false if customer purchase limit is reached for discount
  def cusomter_limit_reached_for_discount?(customer_id)
    return false if customer_id.blank? || limit_per_customer == "unlimited" || limit_per_customer.blank? || limit_per_customer.to_i == 0
    items_purchased_by_customer = cart_items.joins(:cart).where("carts.user_id = ? AND carts.paid = ?", customer_id, true).size
    return true if items_purchased_by_customer >= limit_per_customer.to_i
    return false ##else return false
  end
  
  ##method return true / false if discount purchase reached maximum limit 
  def check_discount_sold_out?
    return false if limit == "unlimited" || limit.blank? || limit.to_i == 0
    no_of_items_purchased = cart_items.joins(:cart).where("carts.paid = true").size
    return true if no_of_items_purchased >= limit.to_i
    return false ##else return false
  end
  
  def max_limit_reached?
    check_discount_sold_out?
  end

  def sold_out?
    sold_out
  end

  def expired?
    expiry_date.present? ? true : false
  end


  def mark_discount_as_sold_out
    Rails.logger.info "Inside Sold out discount:: #{id} Sold Out Date:: #{Date.today}"
    self.update_columns(sold_out: true, expiry_date: (Date.today + 10.days))
  end

  def active?
    active
  end

  private

  def create_slug
  	self.update_column(:slug, "#{id} #{name}".parameterize) if name_changed?
  end
  
  ##add category type for search filters
  def save_pg_search_category
    self.pg_search_document.update_column(:category_type, discount_type) if self.pg_search_document.present? && active
  end

end

app/controllers/affiliates_controller.rb
class AffiliatesController < ApplicationController

	before_action :authenticate_user!
	before_action :check_affiliate_access
  

  def index
  	@affiliate_businesses = current_user.affiliate_businesses
  	@affiliate_discounts = current_user.affiliate_discounts
  	add_breadcrumb "Home", :root_path, data: { turbolinks: false }
  	add_breadcrumb "Affiliations" ##without link
  end
  
  ##create new business profile by affiliate user
	def create_business
		add_breadcrumb "Home", :root_path, data: { turbolinks: false }
  	add_breadcrumb "Affiliations", :affiliations_path
  	add_breadcrumb "Add New Business" ##without link
		@business = Profile.new
		if request.post?

			user_params = params[:user]
			if user_params.present?
			  user = User.where(email: user_params[:email]).first

			  if user.present?
			  	flash[:alert] = "Business user email has already exists in our system."
			  	return render action: :create_business
			  else
			  	##business user
			  	user = User.new
			  	user.email = user_params[:email]
			  	user.user_type = "business"
			  	user.password = user_params[:password]
			  	if user.valid_password?(user_params[:password])
			  	else
			  		flash[:alert] = "Email or Password is invalid, password should be atleast 8 characters."
            return render action: :create_business
			  	end
			  end

			else
				flash[:alert] = "Business User details can't be blank."
				return render action: :create_business
			end

			@business.attributes = profile_params
	    @business.profile_type = "business"
	    @business.affiliate_code = current_user.affiliate_code
	    if @business.save
	    	user.save
	    	@business.update_column(:user_id, user.id)
	      redirect_to affiliations_path, notice: "Business Profile created successfully!!"
	    else
	    	flash[:alert] = "Please fill all fields."
	      render action: :create_business
	    end
		end
	end

	##update business profile by affiliate user
	def update_business
		add_breadcrumb "Home", :root_path, data: { turbolinks: false }
  	add_breadcrumb "Affiliations", :affiliations_path
  	add_breadcrumb "Edit Business" ##without link
		@business = Profile.where(profile_type: 'business', slug: params[:slug]).first
		return redirect_to affiliations_path, alert: "You are not authorized to access this page." if @business.blank?
		return redirect_to root_path, alert: "You are not authorized to access this page." unless @business.affiliated_by?(current_user.affiliate_code)
		if request.put?
			@business.attributes = profile_params
	    if @business.save
	      redirect_to affiliations_path, notice: "Business Profile updated successfully!!"
	    else
	    	lash[:alert] = "Please fill all fields."
	      render action: :update_business
	    end
		end
	end

	def create_discount
		add_breadcrumb "Home", :root_path
  	add_breadcrumb "Affiliations", :affiliations_path
  	add_breadcrumb "Add New Discount" ##without link
  	@affiliate_businesses = current_user.affiliate_businesses.pluck(:name, :id)
		@discount = Discount.new
		if request.post?
			@discount = Discount.new(discount_params)
			business = Profile.where(id: params[:discount][:business_id]).first
			if business.present?
				@discount.latitude = business.latitude
				@discount.longitude = business.longitude
			end
			@discount.affiliate_code = current_user.affiliate_code

			if @discount.save
				redirect_to affiliations_path, notice: "Discount Info created successfully!!"
			else
				flash[:alert] = "Discount Info can't be blank."
				return render action: :create_discount
			end
		end
	end

	def update_discount
		add_breadcrumb "Home", :root_path, data: { turbolinks: false }
  	add_breadcrumb "Affiliations", :affiliations_path
  	add_breadcrumb "Edit Discount" ##without link
  	@affiliate_businesses = current_user.affiliate_businesses.pluck(:name, :id)
		@discount = Discount.where(slug: params[:slug]).first
		return redirect_to affiliations_path, alert: "You are not authorized to access this page." if @discount.blank?
		return redirect_to root_path, alert: "You are not authorized to access this page." unless @discount.affiliated_by?(current_user.affiliate_code)
		if request.put?
			@discount.attributes = discount_params
			business = Profile.where(id: params[:discount][:business_id]).first
			if business.present?
				@discount.latitude = business.latitude
				@discount.longitude = business.longitude
			end

			if @discount.save
				redirect_to affiliations_path, notice: "Discount Info updated successfully!!"
			else
				flash[:alert] = "Discount Info can't be blank."
				return render action: :create_discount
			end
		end
	end


	#####################
  ## Protected Methods
  #####################
  
  protected

  ###################
  ## Private Methods
  ###################

  private

    def discount_params
      params.require(:discount).permit(:name, :description, :discount_type, :price, :discounted_price, :image, :family_friendly, :latitude, :longitude, :active, :affiliate_code, :business_id, :limit, :limit_per_customer, :extra_price, :terms, {category_ids: []})
    end

    def profile_params
      params.require(:profile).permit(:name, :description, :street, :city, :state, :zipcode, :website, :fb_link,
        :twitter_link, :google_link, :image, :cover_image, :family_friendly, :phone_number, :country, :affiliate_code)
    end

	  def check_affiliate_access
	  	return redirect_to root_path, alert: "You are not authorized to access this page." unless current_user.affiliate?
	  end 
end

app/views/affiliates/_business_form.html.slim
= form_for(@business, url: url, html: {multipart: true, method: method}) do |f|
	.prog-form-steps
		.prog-form-step.prog-form-step-1.is-visible
		    = hidden_field_tag "profile_id", @business.try(:id), disabled: true
		
			p Tell Us About Business
			- if show_user_fields
				.field#business-name
				  = email_field_tag "user[email]", nil, placeholder: "Business user email"
				.field#business-name
				  = password_field_tag "user[password]", nil, placeholder: "Business user password"
			.field#business-name
			  = f.text_field :name, placeholder: "Business name"
			.field#business-description
				= f.text_area :description, placeholder: "Business Description"
			p Is Business Family Friendly?
			.field.styled-radio#business-family
				= f.check_box :family_friendly, id: 'styled-radio', class: 'left'
				label.check-label for="styled-radio"
			.prog-form-actions
				/ .btn-secondary-ghost.prog-form-cancel BACK
				.btn.btn-primary.prog-form-next NEXT


		.prog-form-step.prog-form-step-2
			p Where is Business located?
			.field#business-street
				= f.text_field :street, placeholder: "Business Address"
			.field.styled-select
			  = f.select :country, options_for_select(Country.order(:name).pluck(:name), selected: @business.country), prompt: "> Please select a country"
			.field.styled-select
			  = render partial: "pages/states_list"
			.field#business-city
				= f.text_field :city, placeholder: "City"
			.field#business-zip
			  = f.text_field :zipcode, placeholder: "Zipcode"
			.prog-form-actions
				.btn-secondary-ghost.prog-form-back BACK
				.btn.btn-primary.prog-form-next NEXT


		.prog-form-step.prog-form-step-3
			p How can customers reach business?
			.field#business-phone
			  = f.text_field :phone_number, placeholder: "Phone Number"
			.field#business-website
			  = f.text_field :website, placeholder: "Website"
			p Are business on social media?
			.field#business-facebook
			  = f.text_field :fb_link, placeholder: "@Facebook"
			.field#business-twitter
			  = f.text_field :twitter_link, placeholder: "@Twitter"
			.field#business-google
			  = f.text_field :google_link, placeholder: "@Google+"
			.prog-form-actions
				.btn-secondary-ghost.prog-form-back BACK
				.btn.btn-primary.prog-form-next NEXT


		.prog-form-step.prog-form-step-4
			p Make sure business looks great!
			.field#business-profile-image
				label Profile Image
				- if @business.image?
					.form-image
						= image_tag(@business.image.url(:medium))
				= f.file_field :image, placeholder: "Upload Profile Image", class: 'file-field'
			.field#business-cover-image
				label Cover Image
				- if @business.cover_image?
					.form-image
						= image_tag(@business.cover_image.url(:medium))
				= f.file_field :cover_image, placeholder: "Upload Cover Image", class: 'file-field'
			.prog-form-actions
				.btn-secondary-ghost.prog-form-back BACK
				= button_tag "SAVE", class: "btn btn-primary prog-form-next", data: {disable_with: "Saving..."}

app/views/affiliates/_discount_form.html.slim
= form_for(@discount, url: url, html: {multipart: true, method: method, id: "progress_form"}) do |f|

  .prog-form-steps
    .prog-form-step.prog-form-step-1.is-visible
      p Tell Us About Discount
      .field
        = f.text_field :name, placeholder: 'Discount Name', label: ''
      .field
        = f.text_area :description, placeholder: 'Discount Description', label: ''
      .prog-form-actions
        / .btn-secondary-ghost.prog-form-cancel BACK
        .btn.btn-primary.prog-form-next NEXT


    .prog-form-step.prog-form-step-2
      p What Type of Discount Is This?
      .field
        .styled-select
          = f.select :discount_type, options_for_select(Discount::DISCOUNT_TYPES, selected: @discount.discount_type), prompt: "Please select discount type"
      br
      p Is Discount Family Friendly?
      .field.styled-radio
        = f.check_box :family_friendly, id: 'styled-radio', class: 'left'
        label.check-label for="styled-radio"
      br
      p Active?
      .field.styled-radio
        = f.check_box :active, id: 'styled-radio-active', class: 'left'
        label.check-label for="styled-radio-active"
      br
      p Choose Categories
      .field
        = f.select(:category_ids, options_for_select(Category.select(:name, :id).collect{ |c| [c.name, c.id]}, selected: @discount.category_ids),{}, {class: 'multi-select', multiple: true})      
        br
      
      - if affiliate?
        p Business Info
        .field
          .styled-select
            = f.select :business_id, options_for_select(@affiliate_businesses, selected: @discount.business_id), prompt: "Please select a business"   


      .prog-form-actions
        .btn-secondary-ghost.prog-form-back BACK
        .btn.btn-primary.prog-form-next NEXT


    .prog-form-step.prog-form-step-3
      p What is the original price?
      .field
        = f.number_field :price, placeholder: 'Original Price', class: 'number-field'
      br
      p What is the discounted price?
      .field
        = f.number_field :discounted_price, placeholder: 'Discounted Price', class: 'number-field'
      br
      .extra_price
        p What is the extra price?
        .field
          = f.number_field :extra_price, placeholder: 'Extra Price', class: 'number-field'
      .prog-form-actions
        .btn-secondary-ghost.prog-form-back BACK
        .btn.btn-primary.prog-form-next NEXT


    .prog-form-step.prog-form-step-4
      p Maximum Limit
      .field
        = f.text_field :limit, placeholder: 'Maximum Limit'
      p Limit per customer
      .field
        = f.text_field :limit_per_customer, placeholder: 'Limit Per Customer'
      br
      p Add an image to discount
      .field
        - if @discount.image?
          .form-image
            = image_tag(@discount.image.thumb.url)
        - else
          = f.file_field :image, class: 'file-field'
      br
      p = link_to "Choose from default T&C", "javascript:", id: "default_terms_link"
      .field#default_terms
        .styled-select
          = select_tag "default_terms_conditions", options_for_select(DISCOUNT_TERMS_AND_CONDITIONS), prompt: "Please select a terms form the list"
      br
      p Terms
      .field
        = f.cktext_area :terms
      .prog-form-actions
        .btn-secondary-ghost.prog-form-back BACK
        = link_to "SAVE", "javascript:", class: "btn btn-primary prog-form-next", id: "progress_submit_btn"

javascript:
  $(".extra_price").hide();
  $('#discount_discount_type').change(function(){
    val = $(this).val();
    if(val == "product"){
      $(".extra_price").show();
    }else{
      $(".extra_price").hide();
      $('#discount_extra_price').val(0.0);
    }
  });
  if($('#discount_discount_type :selected').val() == "product"){
    $(".extra_price").show();
  }
  $('#default_terms_conditions').change(function(){
    val = $(this).val();
    CKEDITOR.instances['discount_terms'].setData(val);
  });
  
  // JQuery UI Multi Select
  $(function(){
    $('.multi-select').chosen({
      max_selected_options: 3, //Max select limit 
      display_selected_options: true, 
      placeholder_text_multiple: "Select Categories",
      width:"250px"
    });    
  });

app/views/affiliates/create_business.html.slim
section#new-business
	.container
		.center.user-upgrade-form
			.prog-form
				.prog-form-head
					.prog-form-title
					  = render partial: "layouts/flash_messages", flash: flash if flash.present?
						h1 Create New Business
						p Please fill all sections of this form.
					.prog-form-progress
						.prog-circle.is-active
							i.ion-ios-information-outline
						.prog-circle
							i.ion-ios-location-outline
						.prog-circle
							i.ion-ios-world-outline
						.prog-circle
							i.ion-ios-camera-outline
				.prog-form-body
					= render 'affiliates/business_form', url: create_business_path, method: "post", show_user_fields: true
					.center
						= link_to 'Abort!', root_path, data: { turbolinks: false }

app/views/affiliates/create_discount.html.slim
section#new-discount
	.container
		.center.discount-form
			.prog-form
				.prog-form-head
					.prog-form-title
					  = render partial: "layouts/flash_messages", flash: flash if flash.present?	
					  h1.center Discount Info
					  p Please fill all sections of this form.
					.prog-form-progress
						.prog-circle.is-active
							i.ion-ios-information-outline
						.prog-circle
							i.ion-ios-people-outline
						.prog-circle
							i.ion-social-usd-outline
						.prog-circle
							i.ion-ios-camera-outline
					.prog-form-body
						== render 'discount_form', url: create_discount_path, method: "post"
						.center
							= link_to 'Abort!', root_path, data: { turbolinks: false }

app/views/affiliates/index.html.slim
section
  = render partial: "layouts/flash_messages", flash: flash if flash.present?
  h1.left Affiliate Businesses
  = link_to 'Add A Business', create_business_path, class: 'right btn-secondary-ghost'


section#local-businesses-gallery.discounts-gallery
  .container
    .discount-category-block
      ul#featured-profiles
        - @affiliate_businesses.each do |business|
          li.discount-card.bx-shadow-2
            = link_to show_account_path(business.profile_type, business.slug)
              .discount-card-image style="background-image:url(#{business.image});"
            = link_to show_account_path(business.profile_type, business.slug)
              .discount-card-info.dark
                - if business.family_friendly?             
                  i.ion-ios-people
                  i.ion-checkmark-circled
                h2 = business.name
                p = truncate(business.description, :length => 45)
            .discount-card-love
              = link_to 'Edit', update_business_path(business.slug)



section
  h1.left Affiliate Discounts
  - if @affiliate_businesses.size > 0
    = link_to 'Add A Discount', create_discount_path, class: 'right btn-secondary-ghost'
  - else
    = link_to 'Add A Discount', "javascript:", class: 'right btn-secondary-ghost', onclick: 'alert("You are not affiliated with any business!")'


section.discounts-gallery
  .discount-category-block
    - @affiliate_discounts.each do |discount|
      .discount-card.bx-shadow-2
        = link_to discount_path(discount.slug)
          .discount-card-image style="background-image:url(#{discount.image});"
        = link_to discount_path(discount.slug)
          .discount-card-info.dark
            - if discount.family_friendly?             
              i.ion-ios-people
              i.ion-checkmark-circled
            h2 = discount.name
            p = truncate(discount.description, :length => 45)
            
        .discount-card-buy
          p.small 
            | was 
            span 
              | $
              = discount.price
          .discount-card-buy-button.btn-primary 
            | $
            = discount.discounted_price
        .discount-card-love
          = link_to 'Edit', update_discount_path(discount.slug)

app/views/affiliates/update_business.html.slim
section#new-business
	.container
		.center.user-upgrade-form
			.prog-form
				.prog-form-head
					.prog-form-title
					  = render partial: "layouts/flash_messages", flash: flash if flash.present?
						h1 Edit Business
						p Please fill all sections of this form.
					.prog-form-progress
						.prog-circle.is-active
							i.ion-ios-information-outline
						.prog-circle
							i.ion-ios-location-outline
						.prog-circle
							i.ion-ios-world-outline
						.prog-circle
							i.ion-ios-camera-outline
				.prog-form-body
					= render 'affiliates/business_form', url: update_business_path, method: "put", show_user_fields: false
					.center
						= link_to 'Abort!', root_path, data: { turbolinks: false }

app/views/affiliates/update_discount.html.slim
section#new-discount
	.container
		.center.discount-form
			.prog-form
				.prog-form-head
					.prog-form-title
					  = render partial: "layouts/flash_messages", flash: flash if flash.present?	
					  h1.center Edit Discount Info
					  p Please fill all sections of this form.
					.prog-form-progress
						.prog-circle.is-active
							i.ion-ios-information-outline
						.prog-circle
							i.ion-ios-people-outline
						.prog-circle
							i.ion-social-usd-outline
						.prog-circle
							i.ion-ios-camera-outline
					.prog-form-body
						== render 'discount_form', url: update_discount_path, method: "put"
						.center
							= link_to 'Abort!', root_path, data: { turbolinks: false }