config/routes.rb
Rails.application.routes.draw do

	require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
  mount Ckeditor::Engine => '/ckeditor'
  
	devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)
	resources :slides
	resources :discounts
	post '/discounts/:id/like', to: 'discounts#like', as: :discount_like

	post '/pages/save_location', to: 'pages#save_location'
	post '/pages/update_location', to: 'pages#update_location', as: :update_location
	get '/favorite-discounts', to: 'users#favorite_discounts', as: :favorite_discounts
	get '/redeem', to: 'users#redeem', as: :redeem_deals
	get '/my-purchase', to: 'users#my_purchase', as: :my_purchase
	get '/my-sales', to: 'users#my_sales', as: :my_sales
	post '/mark_deal_redeem/:item_id', to: 'users#mark_deal_redeem', as: :mark_deal_redeem
	post '/users/send_deal_as_gift/:item_id', to: 'users#send_deal_as_gift', as: :send_deal_as_gift
	get '/users/accept-deal-gift', to: 'users#accept_deal_gift', as: :accept_deal_gift

	resources :affiliates, only: []
	get '/affiliations', to: 'affiliates#index', as: :affiliations
	match 'affiliates/create_business', to: 'affiliates#create_business', as: :create_business, via: [:get, :post]
	match 'affiliates/update_business/:slug', to: 'affiliates#update_business', as: :update_business, via: [:get, :put]
	match 'affiliates/create_discount', to: 'affiliates#create_discount', as: :create_discount, via: [:get, :post]
	match 'affiliates/update_discount/:slug', to: 'affiliates#update_discount', as: :update_discount, via: [:get, :put]
	post '/pages/load_states', to: 'pages#load_states', as: :load_states
	get '/payout/request', to: 'pages#request_payout', as: :request_payout
	post 'payout/submit_request', to: 'pages#submit_payout_request', as: :submit_payout_request
	

	root 'pages#index'
	get '/search', to: 'pages#search', as: :search
	post '/subscribe', to: 'pages#subscribe', as: :subscribe

	devise_for :users,
	controllers: {registrations: :registrations, omniauth_callbacks: :omniauth_callbacks, sessions: :sessions}

	as :user do
		get "/login", to: 'sessions#new'
		post "/login", to: 'sessions#create'
		get '/join', to: 'registrations#new'
		post '/join', to: 'registrations#create'
		delete '/logout', to: 'sessions#destroy'
		get '/forgot_password', to: 'devise/passwords#new'
		post '/forgot_password', to: 'devise/passwords#create'
		get '/account', to: 'registrations#edit'
		put '/account', to: 'registrations#update'
		get '/profile', to: 'users#profile'
		get '/:type/:slug', to: 'pages#show_account', as: :show_account
		post 'update_profile', to: 'users#update_profile'
		get '/merchant_account', to: 'users#merchant_account', as: :merchant_account
	end
  get '/stripe_connect', to: 'users#stripe_connect', as: :stripe_connect
  get '/stripe_connect_callback', to: 'users#stripe_connect_callback', as: :stripe_connect_callback
  
  resources :carts, only: []
	get '/cart', to: 'carts#index', as: :carts
	post '/add_to_cart', to: 'carts#add_to_cart', as: :add_to_cart
	delete '/remove_from_cart', to: 'carts#remove_from_cart', as: :remove_from_cart
	post '/checkout', to: "carts#checkout", as: :checkout
	post '/carts/purchase', to: "carts#purchase", as: :purchase
	get '/purchase/invoice/:purchase_number', to: "carts#invoice", as: :invoice

	get '/deals', to: 'pages#discounts'
	get '/businesses', to: 'pages#businesses'
	get '/organizations', to: 'pages#organizations'
	get '/products', to: 'pages#products'

	get '/about', to: 'pages#about'
	get '/contact', to: 'pages#contact'
	get '/terms', to: 'pages#terms'
	get '/privacy', to: 'pages#privacy'
	get '/faq', to: 'pages#faq'
	get '/learn', to: 'pages#learn'
	get '/charity', to: 'pages#charity'
	get '/autism', to: 'pages#autism'
	get '/for-business', to: 'pages#for_business'
	get '/welcome-back', to: 'pages#welcome_back'

end

app/models/discount.rb
class Discount < ApplicationRecord

  include PgSearch
  multisearchable against: [:name, :description], using: { tsearch: {any_word: true, prefix: true } , trigram: {:threshold => 0.1}}, if: :active?
  #pg_search_scope :custom_search, :against => [:name, :description], if: :active?

  mount_uploader :image, DiscountImageUploader

  validates :name, :description, :image, :price, :discounted_price, :discount_type, :business_id, :limit, :limit_per_customer, presence: true

  belongs_to :business, class_name: "Profile", foreign_key: :business_id
  has_many :likes
  has_and_belongs_to_many :categories
  has_many :cart_items

  DISCOUNT_TYPES = [['Deal', 'deal'], ['Product', 'product']]
  
  after_save :create_slug, :save_pg_search_category

  scope :only_active, -> { where(discount_type: 'deal', active: true) }
  scope :only_active_products, -> { where(discount_type: 'product', active: true) }

  geocoded_by :address

  attr_accessor :default_terms_conditions

  def address
    [business.street, business.city, business.state, business.zipcode, business.country].compact.join(', ')
  end

  def to_param
    slug
  end

  def affiliated_by?(user_affiliated_code)
    affiliate_code == user_affiliated_code
  end

  def owned_by?(user)
  	business_id == user.try(:profile).try(:id)
  end

  ##check if discount is already liked by a user
  def liked?(user_id)
    likes.collect(&:user_id).include?(user_id)
  end
  
  ##method return true / false if customer purchase limit is reached for discount
  def cusomter_limit_reached_for_discount?(customer_id)
    return false if customer_id.blank? || limit_per_customer == "unlimited" || limit_per_customer.blank? || limit_per_customer.to_i == 0
    items_purchased_by_customer = cart_items.joins(:cart).where("carts.user_id = ? AND carts.paid = ?", customer_id, true).size
    return true if items_purchased_by_customer >= limit_per_customer.to_i
    return false ##else return false
  end
  
  ##method return true / false if discount purchase reached maximum limit 
  def check_discount_sold_out?
    return false if limit == "unlimited" || limit.blank? || limit.to_i == 0
    no_of_items_purchased = cart_items.joins(:cart).where("carts.paid = true").size
    return true if no_of_items_purchased >= limit.to_i
    return false ##else return false
  end
  
  def max_limit_reached?
    check_discount_sold_out?
  end

  def sold_out?
    sold_out
  end

  def expired?
    expiry_date.present? ? true : false
  end


  def mark_discount_as_sold_out
    Rails.logger.info "Inside Sold out discount:: #{id} Sold Out Date:: #{Date.today}"
    self.update_columns(sold_out: true, expiry_date: (Date.today + 10.days))
  end

  def active?
    active
  end

  private

  def create_slug
  	self.update_column(:slug, "#{id} #{name}".parameterize) if name_changed?
  end
  
  ##add category type for search filters
  def save_pg_search_category
    self.pg_search_document.update_column(:category_type, discount_type) if self.pg_search_document.present? && active
  end

end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController

  before_action :authenticate_user!, except: [:show, :like]
  before_action :set_discount, only: [:show, :edit, :update, :destroy, :like]
  before_action :check_busniess_access, only: [:edit, :new, :create, :update, :destroy]
  before_action :set_business, only: [:show, :edit, :update, :new, :create, :update, :index]
 
  ###########
  ## Filters
  ###########
  ############
  ## Requires
  ############
  #############
  ## Constants
  #############
  ##################
  ## Public Actions
  ##################

  def index
    return redirect_to root_path unless current_user.business?
    return redirect_to root_path, alert: "You must have an active business profile to view this section." if @business.blank?
    @discounts = @business.discounts.includes(:likes)
    make_breadcrumbs  
  end

  def show
    return redirect_to root_path, alert: "Either discount does not exists or is inactive." unless @discount.active
    make_breadcrumbs("show")##call breadcrumbs
    ##set page SEO
    set_page_seo
    
    if Rails.env.development? || Rails.env.staging?
      @merchant_account = MerchantAccount.where(livemode: false, profile_id: @discount.business_id).first.present?
    else
      @merchant_account = MerchantAccount.where(livemode: true, profile_id: @discount.business_id).first.present?
    end

  end

  def new
    return redirect_to discounts_path, alert: "You have to link your stripe merchant account with MarketPad before creating discounts." if @business.merchant_accounts.blank?
    @discount = Discount.new
    make_breadcrumbs("new")##call breadcrumbs
    @existing_affiliates = get_existing_affiliates
  end

  def edit
    return redirect_to root_path unless @discount.owned_by?(current_user)
    make_breadcrumbs("edit")##call breadcrumbs
    @existing_affiliates = get_existing_affiliates
  end

  def create
    @existing_affiliates = get_existing_affiliates
    make_breadcrumbs("new")##call breadcrumbs
    @discount = Discount.new(discount_params)
    @discount.business_id = current_user.profile.id
    respond_to do |format|
      if @discount.save
        format.html { redirect_to @discount, notice: 'Discount was successfully created.' }
        format.json { render :show, status: :created, location: @discount }
      else
        format.html { render :new }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @existing_affiliates = get_existing_affiliates
    make_breadcrumbs("edit")##call breadcrumbs
    respond_to do |format|
      if @discount.update(discount_params)
        format.html { redirect_to discounts_path, notice: 'Discount was successfully updated.' }
        format.json { render :show, status: :ok, location: @discount }
      else
        format.html { render :edit }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @discount.destroy
    respond_to do |format|
      format.html { redirect_to discounts_url, notice: 'Discount was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  ##handle discount like / unlike request
  def like
    if current_user.blank?
      session[:return_url] = request.referer
      render js: "window.location = '#{login_path}'"
    else
      liked = current_user.likes.where(discount_id: @discount.id).first
      if liked.present? ##already liked it, remove from like table
        liked.delete
        @msg = "Removed from Favorites!!"
        @status = "unliked"
      else ## like
        Like.create(discount_id: @discount.id, user_id: current_user.id)
        @msg = "Added to Favorites!!"
        @status = "liked"
      end
    end
  end

  #####################
  ## Protected Methods
  #####################
  
  protected

  ###################
  ## Private Methods
  ###################

  private

    def set_page_seo
      @page_title = "#{@discount.name}"
    end
    
    ##create breadcrumbs here
    def make_breadcrumbs(page_type = nil)
      add_breadcrumb "Home", :root_path, data: { turbolinks: false }
      add_breadcrumb @business.name, "#{show_account_path(@business.profile_type, @business.slug) }" if @business.present?
      add_breadcrumb "My Discounts", discounts_path if current_user.present? && current_user.business? ##show this link only to business accounts
      add_breadcrumb "New Discount" if page_type == "new" ##without link 
      add_breadcrumb "Edit Discount" if page_type == "edit" ##without link
      add_breadcrumb @discount.name if page_type == "show" ##without link 

    end

    def set_discount
      @discount = Discount.where(slug: params[:id]).first
      return redirect_to root_path if @discount.blank?
    end

    def check_busniess_access
      return redirect_to root_path, alert: "You are not authorized to access this page." unless current_user.business?
      return redirect_to root_path, alert: "You must have an active business profile to create a discount." if current_user.profile.blank?
    end

    def set_business
      @business = @discount.present? ? @discount.business : current_user.profile
    end

    def discount_params
      params.require(:discount).permit(:name, :description, :discount_type, :price, :discounted_price, :image, :family_friendly, :latitude, :longitude, :active, :affiliate_code, :limit, :limit_per_customer, :extra_price, :terms, {category_ids:  []})
    end
    
    #return existing affiliates on new / edit discount form
    def get_existing_affiliates
      existing_affiliats = []
      existing_affiliats << @business.try(:affiliate_code)
      existing_affiliats << @business.discounts.where("affiliate_code is not null").select(:affiliate_code).collect(&:affiliate_code)
      existing_affiliats.flatten.compact.uniq
    end

end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/views/discounts/_form.html.slim
= form_for(@discount, html: {multipart: true, id: "progress_form"}) do |f|
  = render partial: 'users/errors', locals: {object: @discount}
  .prog-form-steps
    .prog-form-step.prog-form-step-1.is-visible
      p Tell Us About Your Discount
      .field
        = f.text_field :name, placeholder: 'Discount Name', label: ''
      .field
        = f.text_area :description, placeholder: 'Discount Description', label: ''
      .field
        = f.hidden_field :latitude, value: @business.try(:latitude)
        = f.hidden_field :longitude, value: @business.try(:longitude)
      .prog-form-actions
        / .btn-secondary-ghost.prog-form-cancel BACK
        .btn.btn-primary.prog-form-next NEXT


    .prog-form-step.prog-form-step-2
      p What Type of Discount Is This?
      .field
        .styled-select
          = f.select :discount_type, options_for_select(Discount::DISCOUNT_TYPES, selected: @discount.discount_type), prompt: "Please select discount type"
      br
      p Is Your Discount Family Friendly?
      .field.styled-radio
        = f.check_box :family_friendly, id: 'styled-radio', class: 'left'
        label.check-label for="styled-radio"
      br
      p Active?
      .field.styled-radio
        = f.check_box :active, id: 'styled-radio-active', class: 'left'
        label.check-label for="styled-radio-active"
      br
      p Choose Categories
      .field.styled-select
        = f.select(:category_ids, options_for_select(Category.select(:name, :id).collect{ |c| [c.name, c.id]}, selected: @discount.category_ids),{}, {class: 'multi-select', multiple: true})
      br
      p Affiliate Code
      .field
        = f.text_field :affiliate_code, placeholder: 'New Affiliate Code'
    
      - if @existing_affiliates.present? 
        br
        p = link_to "Choose from existing Affiliate", "javascript:", id: "existing_affiliate_link"
        .field#existing_affiliates
          .styled-select
            = select_tag "existing_affiliate_code", options_for_select(@existing_affiliates, selected: @discount.affiliate_code), prompt: "Please select a affiliate"   
          

      .prog-form-actions
        .btn-secondary-ghost.prog-form-back BACK
        .btn.btn-primary.prog-form-next NEXT


    .prog-form-step.prog-form-step-3
      p What is the original price?
      .field
        = f.number_field :price, placeholder: 'Original Price', class: 'number-field'
      br
      p What is the discounted price?
      .field
        = f.number_field :discounted_price, placeholder: 'Discounted Price', class: 'number-field'
      br
      .extra_price
        p What is the extra price?
        .field
          = f.number_field :extra_price, placeholder: 'Extra Commission Incentive', class: 'number-field'
      .prog-form-actions
        .btn-secondary-ghost.prog-form-back BACK
        .btn.btn-primary.prog-form-next NEXT


    .prog-form-step.prog-form-step-4
      p Maximum Limit
      .field
        = f.text_field :limit, placeholder: 'How many can be sold in total?'
      br
      p Limit per customer
      .field
        = f.text_field :limit_per_customer, placeholder: 'How many can each customer buy?'
      br
      p Add an image to your discount
      .field
        - if @discount.image?
          .form-image
            = image_tag(@discount.image.thumb.url)
        - else
          = f.file_field :image, class: 'file-field'
      br
      p = link_to "Choose from default T&C", "javascript:", id: "default_terms_link"
      .field#default_terms
        .styled-select
          = select_tag "default_terms_conditions", options_for_select(DISCOUNT_TERMS_AND_CONDITIONS), prompt: "Please select a terms form the list"
      br
      p Terms
      .field
        = f.cktext_area :terms
      br
      .prog-form-actions
        .btn-secondary-ghost.prog-form-back BACK
        = link_to "SAVE", "javascript:", class: "btn btn-primary prog-form-next", id: "progress_submit_btn"

javascript:
  $(".extra_price").hide();
  $('#discount_discount_type').change(function(){
    val = $(this).val();
    if(val == "product"){
      $(".extra_price").show();
    }else{
      $(".extra_price").hide();
      $('#discount_extra_price').val(0.0);
    }
  });

  if($('#discount_discount_type :selected').val() == "product"){
    $(".extra_price").show();
  }
  //$('#existing_affiliate_link').click(function(){
    //$('#existing_affiliates').toggle();
  //});

  $('#existing_affiliate_code').change(function(){
    val = $(this).val();
    $('#discount_affiliate_code').val(val);
  });

  $('#default_terms_conditions').change(function(){
    val = $(this).val();
    CKEDITOR.instances['discount_terms'].setData(val);
  });

  // JQuery UI Multi Select
  $(function(){
    $('.multi-select').chosen({
      max_selected_options: 3, //Max select limit 
      display_selected_options: true, 
      placeholder_text_multiple: "Select Categories",
      width:"250px"
    });    
  });
  

app/views/discounts/edit.html.slim
section#edit-discount
	.container
		.center.discount-form
			.prog-form
				.prog-form-head
					.prog-form-title	
					    h1.center Discount Info
					    p Please fill all sections of this form.
					.prog-form-progress
						.prog-circle.is-active
							i.ion-ios-information-outline
						.prog-circle
							i.ion-ios-people-outline
						.prog-circle
							i.ion-social-usd-outline
						.prog-circle
							i.ion-ios-camera-outline
					.prog-form-body
						== render 'form'
						.center
							= link_to 'Abort!', root_path, data: { turbolinks: false }

app/views/discounts/index.html.slim
section
  h1.left My Discounts
  - if @business.merchant_accounts.present?
    = link_to 'Add A Discount', new_discount_path, class: 'right btn-secondary-ghost'
  - else
    = link_to 'Add A Discount', "javascript:", class: 'right btn-secondary-ghost', onclick: 'alert("You have to link your stripe merchant account with MarketPad  before creating discounts.")'


section.discounts-gallery
  .discount-category-block
    - @discounts.each do |discount|
      .discount-card.bx-shadow-2
        = link_to discount_path(discount.slug)
          .discount-card-image style="background-image:url(#{discount.image});"
        = link_to discount_path(discount.slug)
          .discount-card-info.dark
            - if discount.family_friendly?             
              i.ion-ios-people
              i.ion-checkmark-circled
            h2 = discount.name
            p = truncate(discount.description.html_safe, :length => 45)
            
        .discount-card-buy
          p.small 
            | was 
            span = number_to_currency(discount.price)
          .discount-card-buy-button.btn-primary 
            = number_to_currency(discount.discounted_price)
        .discount-card-love
          = link_to "Edit", edit_discount_path(discount.slug)

app/views/discounts/like.js.erb
<% if @status == "liked" %>
  $('#discount_like_'+'<%= @discount.id %>').html("<i class='ion-ios-heart'></i>")
<% elsif @status == "unliked" %>
  $('#discount_like_'+'<%= @discount.id %>').html("<i class='ion-ios-heart-outline'></i>")
<% end %>

app/views/discounts/new.html.slim
section#new-discount
	.container
		.center.discount-form
			.prog-form
				.prog-form-head
					.prog-form-title	
					    h1.center Discount Info
					    p Please fill all sections of this form.
					.prog-form-progress
						.prog-circle.is-active
							i.ion-ios-information-outline
						.prog-circle
							i.ion-ios-people-outline
						.prog-circle
							i.ion-social-usd-outline
						.prog-circle
							i.ion-ios-camera-outline
					.prog-form-body
						== render 'form'
						.center
							= link_to 'Abort!', root_path, data: { turbolinks: false }

app/views/discounts/show.html.slim
- sold_out = @discount.sold_out?
#discount-show
  .container-narrow
    .discount-hero
      .discount-show-image style="background-image: url(#{@discount.image.medium.url})"
      .discount-show-title
        .center
          - if @discount.family_friendly?             
            i.ion-ios-people
            i.ion-checkmark-circled
        h1.center = @discount.name
        h5.center = @discount.business.name
      .discount-show-price.center.hide-tablet
        h2 #{sold_out ? "SOLD OUT" : "BUY NOW"}
        .center.small
          h4 was &nbsp;
          h3 
            = number_to_currency(@discount.price)
        - if sold_out
          = link_to "javascript:", method: :post, class: 'btn btn-primary'
            = number_to_currency(@discount.discounted_price)
        - else
          - if @discount.cusomter_limit_reached_for_discount?(current_user.try(:id))
            = link_to "javascript:", onclick: "alert('You can only purchase #{@discount.limit_per_customer} same discounts.')", class: 'btn btn-primary'
              = number_to_currency(@discount.discounted_price)
          - if @merchant_account
            = link_to add_to_cart_path(discountID: @discount.slug, refererType: params[:refererType], refererID: params[:refererID]), method: :post, class: 'btn btn-primary right'
              = number_to_currency(@discount.discounted_price)
          - else
            = link_to "$ #{@discount.discounted_price}", "javascript:", class: 'btn btn-primary', onclick: "alert('#{@discount.business.name} does not accept payments this time, so this item can not be added in your cart.')"


      hr.hide-laptop-up

    .discount-description
      h4.small About this Deal
      p = @discount.description.try(:html_safe)
      hr
    - if @discount.terms?
      .discount-terms
        h4.small Terms & Conditions
        p = @discount.terms.try(:html_safe)
        hr
    .business-description
      h4.small About this Business
      .business-description-logo.left
        = image_tag(@discount.business.image.url(:thumb)) if @discount.business.image.present?
      .business-description-info.clearfix
        h3 = @discount.business.name
        h5 = @discount.business.street
        h5 #{@discount.business.city}, #{@discount.business.state} #{@discount.business.zipcode} #{@discount.business.country}
      .business-description-text
        p = @discount.business.try(:description).try(:html_safe)
      hr
    .business-description-map
      iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDpY_o4sSn89UfroI8QHehYcGWja27tD3o&q=#{@discount.address}" frameborder="0" style="border:0"    
    .buy-discount
      .buy-discount-share.left
        i.ion-android-share-alt
      .left
        h2 #{sold_out ? "SOLD OUT" : "BUY NOW"}
        h4.small.left was &nbsp;
        h3.left 
          = number_to_currency(@discount.price)
      - if sold_out
        = link_to "javascript:", class: 'btn btn-primary right'
          = number_to_currency(@discount.discounted_price)
      - else
        - if @discount.cusomter_limit_reached_for_discount?(current_user.try(:id))
          = link_to "$ #{@discount.discounted_price}", "javascript:", class: 'btn btn-primary', onclick: "alert('You can only purchase #{@discount.limit_per_customer} same discounts.')"
        - else
          - if @merchant_account
            = link_to add_to_cart_path(discountID: @discount.slug, refererType: params[:refererType], refererID: params[:refererID]), method: :post, class: 'btn btn-primary right'
              = number_to_currency(@discount.discounted_price)
          - else
            = link_to "$ #{@discount.discounted_price}", "javascript:", class: 'btn btn-primary', onclick: "alert('#{@discount.business.name} does not accept payments this time, so this item can not be added in your cart.')"